version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Running tests...
      - npm test
  post_build:
    commands:
      - echo Build completed successfully!

artifacts:
  files:
    - app.js
    - package.json
    - node_modules/**/*
  discard-paths: no
